decaffeinate/decaffeinate-parser

- src/util/lineColumnMapper.js
This error occurs when parsing sources that begin with newlines:
```
Error: unexpected 'null' index, perhaps you forgot to check the result of 'indexOfTokenContainingSourceIndex'?
```
This fix simply corrects the `indexOf` usage in this loop, which didn't previously support empty lines.
Same as https://github.com/decaffeinate/decaffeinate-parser/pull/5, but simpler fix.
> Fix lineColumnMapper for sources beginning with newlines

- package.json
- src/parser.js
- src/util/ParseContext.js
We should only be using the tokens generated by coffee-lex.
> Remove methods depending on deprecated CS tokens.

- package.json
- rollup.config.js
- src/parser.js
- test/examples/nested-code-with-outdent/input.coffee
- test/examples/nested-code-with-outdent/output.json
- test/util/isInterpolatedString_test.js
This replaces all usages of the coffee-script package with
decaffeinate-coffeescript, and adds a test that is fixed by the update. Before
the update, most nodes in the test had a range that went to the end of the file.
> fix: update to CoffeeScript fork to fix bug in location data

- src/util/parseLiteral.js
- test/util/parseLiteral_test.js
It turns out that CoffeeScipt's algorithm for removing whitespace from
herestring has a number of subtle cases and bugs that decaffeinate wasn't
properly replicating. This commit should hopefully fix all of those.
This commit also adds a number of tests that compare decaffeinate parsing
directly to CoffeeScript parsing, so hopefully that should provide more
confidence that the two are really equivalent.
Closes https://github.com/decaffeinate/decaffeinate/issues/393.
> fix: properly remove whitespace within herestrings

- src/util/parseLiteral.js
- test/util/parseLiteral_test.js
This is an edge case that wasn't handled that ended up causing a build break in
a decaffeinate test:
https://github.com/decaffeinate/decaffeinate/pull/422
> fix: ignore whitespace-only lines when calculating herestring indent level

- src/parser.js
This should prevent potential future bugs that could cause an infinite loop
(although all known cases causing an infinite loop have been fixed).
> fix: add infinite loop safeguards in string interpolation code

- src/parser.js
- test/examples/comment-only-file/input.coffee
- test/examples/comment-only-file/output.json
Closes https://github.com/decaffeinate/decaffeinate/issues/352
There was already a check for empty programs that just checked if the source
code had length zero, but that didn't handle cases where there was a comment.
Now, we check if the CoffeeScript AST is a block with zero statements.
> fix: handle programs that only contain comments

- src/parser.js
- test/examples/post-for/input.coffee
- test/examples/post-for/output.json
Fixes https://github.com/decaffeinate/decaffeinate/issues/333
Fixes https://github.com/decaffeinate/decaffeinate/issues/502
The code to fix CoffeeScript location data was incorrectly assuming that the
last node of a loop is the loop body, but that isn't true in postfix loops, so
it was causing the end location to be artificially early. Probably, the ideal
behavior (assuming location data actually needs to be fixed here) is to take the
max of all nodes, but that didn't seem trivial. Instead, an easy fix is to just
do the same thing we do for the `if` case: just use the body to extend the
bounds if necessary, but never shrink it. This also seems more robust in
general, probably. At the very least, it's really simple and doesn't break any
decaffeinate tests.
> fix: don't shrink loop bounds by assuming the body is at the end

- package.json
- src/parser.js
- src/util/isStringAtPosition.js
- src/util/parseLiteral.js
- test/examples/chain-calls-with-parens/output.json
- test/examples/chain-calls-without-indent/output.json
- test/examples/chain-calls-without-parens/output.json
- test/examples/multiline-string-with-interpolations-and-quotes/output.json
- test/examples/multiline-string-with-quoted-interpolations-and-non-interpolations/output.json
- test/examples/nested-string-interpolation/output.json
- test/examples/string-ending-with-interpolation/output.json
- test/examples/string-interpolation-in-object-literal/output.json
- test/examples/string-interpolation-plus-normal-string/output.json
- test/examples/string-interpolation-preceded-by-parenthesis/output.json
- test/examples/string-interpolation-with-escaped-newline/output.json
- test/examples/string-interpolation-with-plus/output.json
- test/examples/string-starting-with-interpolation/output.json
- test/examples/string-with-double-quotes/output.json
- test/examples/string-with-interpolation/output.json
- test/examples/string-with-interpolations-at-start-and-end/output.json
- test/examples/string-with-noop-escape/output.json
- test/examples/string-with-only-multiple-interpolations/output.json
- test/examples/string-with-only-single-interpolation/output.json
- test/examples/string-with-parentheses-inside/output.json
- test/examples/string-with-single-quotes/output.json
- test/examples/string-with-triple-double-quotes/output.json
- test/examples/string-with-triple-quote-interpolation-containing-quotes/output.json
- test/examples/string-with-triple-quote-interpolation/output.json
- test/examples/string-with-triple-single-quotes/output.json
- test/util/parseLiteral_test.js
Progress toward these issues:
https://github.com/decaffeinate/decaffeinate/issues/557
https://github.com/decaffeinate/decaffeinate/issues/556
https://github.com/decaffeinate/decaffeinate/issues/554
https://github.com/decaffeinate/decaffeinate/issues/406
This change reworks the string representation in the decaffeinate-parser AST to
better fit the new way of thinking about strings:
* A simple string like `"Hello world"` is seen as a template string with 0
interpolations rather than as something different from a template string.
* Herestrings and regular strings generally just differ in how the lexer treats
them, rather than them being fundamentally different types of nodes. The
coffee-lex output was intentionally designed so that the same (or nearly the
same) code path can be used to …
> refactor: always use the String node type for strings

- package.json
This doesn't really affect anything; I've never really used it. This does not remove semantic-release.
> chore: remove conventional changelog

- src/parser.js
- test/examples/backticks-with-string-inside/input.coffee
- test/examples/backticks-with-string-inside/output.json
Fixes https://github.com/decaffeinate/decaffeinate/issues/576
Previously, we used string matching to figure out what type of literal the node
was, but this can't work by itself because inline JS just includes the JS
contents as the value, so `'a'` has the same CoffeeScript AST representation
whether or not it is surrounded in backticks. Instead, we can look at the
coffee-lex tokens and see if the literal corresponds to a `JS` token.
While I was at it, I also changed the heregex case to use tokens instead of
string matching.
> fix: don't crash when inline JS ends in a close-quote

- package.json
- src/parser.js
Progress toward https://github.com/decaffeinate/decaffeinate/issues/612
Previously, we did a linear search from the end of the token list until we found
a token in the right place. Now, we start the search from just after the end of
the node. We still include the bounds as part of the predicate, since
`indexOfTokenNearSourceIndex` just gives a good upper bound but not necessarily
an exact starting point.
> fix: improve performance when adjusting node bounds

- src/parser.js
- test/examples/loop/output.json
BREAKING CHANGE: Rather than a `While` node with a virtual condition
and null for other properties, this introduces a new `Loop` node that
only has a body.
> refactor: introduce a `Loop` node type

- src/mappers/mapAny.ts
- src/mappers/mapValue.ts
- src/nodes.ts
- src/parser.js
The main problem with doing this refactor in pieces is that they are mutually exclusive code paths. This means that once a call into `mapAny` or any of the concrete mappers happens within parser.js, all descendants of that node must be mappable with that system. Since most node types that contain children can contain essentially anything, this makes it tricky to do anything but all-or-nothing.
In this PR, I introduce not only a `mapValue` and the assiociated `Value` node, but a way to fall back to the old way of mapping. This way, if the mapper fails (likely because it cannot handle a particular node type), it will unwind back to the place we entered the mapper code path and continue as before. The downside is that we have to keep both code paths until we can switch everything over.
> refactor: introduce `mapValue` for handling values

- src/mappers/mapLiteral.ts
- src/parser.js
This replicates the old (incorrect) behavior of creating `Identifier` nodes for `Literal` nodes that we don't know how to parse. This should make decaffeinate work with decaffeinate-parser again.
> fix: create `Identifier` nodes for unknown literals

- package.json
- src/mappers/mapLiteral.ts
This is the proper fix for decaffeinate/decaffeinate#682, specifically updating coffee-lex to lex numbers with a leading period as a single token.
> fix: redo fix for floats with leading periods

- src/mappers/mapLiteral.ts
- src/parser.js
Since `Literal` doesn't have any children, it's pretty simple to handle the fallback in `mapLiteral` itself.
> refactor: move the fallback to `Identifier` to `mapLiteral`

- src/nodes.ts
- src/parser.js
This will allow us to make incremental progress on moving to the mapper functions without doing much to parser.js for a bit. Also, I renamed `Return#argument` to `Return#expression` to match the existing property name.
The downside of this is that it will likely increase parse times as we attempt to map a bunch of nodes we can't handle yet and unwind the stack. I haven't attempted to test this theory, but my gut says that it's not a big deal.
> refactor: try every node with the new mappers with fallbacks

- package.json
- src/mappers/mapAny.ts
- src/mappers/mapParam.ts
- src/nodes.ts
We can't remove the old implementation because parameter default values can contain essentially arbitrary code.
> refactor: extract handling of `Param` to `mapParam`

- src/mappers/mapLiteral.ts
- src/nodes.ts
- test/examples/break/input.coffee
- test/examples/break/output.json
- test/examples/continue/input.coffee
- test/examples/continue/output.json
BREAKING CHANGE: Previously, these statements were mapped to `Identifier`, which was fine because decaffeinate just passed them through anyway. However, it's not the right representation for these statements so this introduces new nodes to represent them.
Fixes #92
> fix: map `break` and `continue` to `Break` and `Continue` nodes

- test/examples/post-while-with-loop/input.coffee
- test/examples/post-while-with-loop/output.json
I suspected that this might fail because we look for a `LOOP` token at the start of the `While` node. If this does pass, perhaps it indicates that the "start" of the `While` node is actually the `WHILE` token rather than the prefixed body.
> test: add a test for a post-while starting with a `loop` token

- package.json
- src/mappers/mapAny.ts
- src/mappers/mapBlock.ts
- src/mappers/mapCode.ts
- src/mappers/mapExtends.ts
- src/mappers/mapParens.ts
- src/mappers/mapRange.ts
- src/mappers/mapSplat.ts
- src/mappers/mapTry.ts
- src/mappers/mapWhile.ts
- src/nodes.ts
- test/examples/for-comprehension/output.json
- test/examples/post-for/output.json
- test/examples/while-on-one-line/output.json
I did a bunch at once to coalesce the type errors that I had to fix in decaffeinate-coffeescript into a single version bump (11→12). The only change in this commit that should affect the output in a meaningful way is that some `Block` nodes which were not previously considered inline now are considered inline. This is due to a change from looking at source code for a preceding newline to using the tokens from coffee-lex, which is hopefully more accurate.
> refactor: add several mappers for various node types

- src/nodes.ts
- src/parser.js
- test/test.js
The approach of using fallbacks when necessary has allowed us to do the transition to mappers/TypeScript in pieces. This is good, but it has the downside that bugs in the fallback code may be masked when a mapper works with the example code but not with real code which triggers the buggy fallback. This commit runs all examples twice, once with mappers+fallbacks, the other with only fallbacks. Doing so ensures that both code paths work as expected. To run with only mappers (and thus see what is left to port), run with `USE_FALLBACK=false`.
> test: check examples with and without mappers

- package.json
- src/mappers/mapAny.ts
- src/mappers/mapOp.ts
- src/nodes.ts
- src/util/isChainedComparison.ts
All CoffeeScript operators are represented using the `Op` node, but with different `operator` values. This adds mappers for just the `-` and `*` operators.
> refactor: add mappers for a few `Op` node types

- src/mappers/mapOp.ts
- src/nodes.ts
- src/parser.js
- test/examples/yield-return-empty/input.coffee
- test/examples/yield-return-empty/output.json
- test/examples/yield-return/input.coffee
- test/examples/yield-return/output.json
Progress toward https://github.com/decaffeinate/decaffeinate/issues/688
> feat: add support for `yield return`

- src/mappers/mapCall.ts
- src/mappers/mapClass.ts
- src/nodes.ts
- src/parser.js
- test/examples/class-super-call/output.json
BREAKING CHANGE: Previously, we made a bare super call (i.e. `super`) just another `FunctionApplication` with a virtual spread argument. This replaces the whole call with a new node type, `BareSuperFunctionApplication`, with no callee or arguments.
> refactor: add mapper support for `super` calls and soaked calls

- src/util/getOperatorInfoInRange.ts
> docs: add documentation for `getOperatorInfoInRange`

- src/mappers/mapArr.ts
- src/mappers/mapAssign.ts
- src/mappers/mapBase.ts
- src/mappers/mapBlock.ts
- src/mappers/mapBool.ts
- src/mappers/mapCall.ts
- src/mappers/mapClass.ts
- src/mappers/mapCode.ts
- src/mappers/mapExistence.ts
- src/mappers/mapExtends.ts
- src/mappers/mapFor.ts
- src/mappers/mapIf.ts
- src/mappers/mapIn.ts
- src/mappers/mapLiteral.ts
- src/mappers/mapNull.ts
- src/mappers/mapObj.ts
- src/mappers/mapOp.ts
- src/mappers/mapParam.ts
- src/mappers/mapParens.ts
- src/mappers/mapRange.ts
- src/mappers/mapReturn.ts
- src/mappers/mapSplat.ts
- src/mappers/mapSwitch.ts
- src/mappers/mapThrow.ts
- src/mappers/mapTry.ts
- src/mappers/mapUndefined.ts
- src/mappers/mapValue.ts
- src/mappers/mapWhile.ts
- src/nodes.ts
- test/test.js
BREAKING CHANGE: This is technically a breaking change since the `virtual` property is no longer present, even though it previously was only ever false. They're no longer needed since we removed all the nodes that required them.
> refactor: remove virtual nodes

- src/util/isChainedComparison.ts
- src/util/isComparisonOperator.ts
- src/util/unwindChainedComparison.ts
- test/examples/chained-comparison-with-other-operators/input.coffee
- test/examples/chained-comparison-with-other-operators/output.json
Fixes https://github.com/decaffeinate/decaffeinate/issues/811
We can't just traverse down any binary operator, there's a specific set of
comparison operators that are eligible for chained comparisons. We already had
this elsewhere in the code, so I just extracted that function and used it.
> fix: only consider comparison operations in chained comparisons

- src/mappers/mapClass.ts
- test/examples/class-with-parenthesized-value/input.coffee
- test/examples/class-with-parenthesized-value/output.json
Fixes https://github.com/decaffeinate/decaffeinate/issues/813
As with a few other cases, it's not actually safe to say that the range of a
node is from the start of the leftmost child to the end of the rightmost child,
since nodes can be wrapped in parens, so we call `mapBase` instead.
> fix: use proper location data for parenthesized class values

- src/mappers/mapClass.ts
- src/nodes.ts
- test/examples/external-constructor/input.coffee
- test/examples/external-constructor/output.json
Progress toward https://github.com/decaffeinate/decaffeinate/issues/830
Constructors are allowed to be arbitrary expressions in CoffeeScript, so I think
the right approach is for the parser to use the `Constructor` node even if the
value isn't a function, and decaffeinate will figure out the right way to handle
it.
> fix: use `Constructor` node even for external constructors

- package.json
Fixes https://github.com/decaffeinate/decaffeinate/issues/931
By using an exact version of decaffeinate-coffeescript, we can avoid differences
between npm and yarn when resolving the right version.
> fix: use the right decaffeinate-coffeescript when installing with yarn

- src/parser.js
- src/util/ParseContext.ts
- src/util/getTemplateLiteralComponents.ts
- src/util/isImplicitPlusOp.ts
Previously, we would convert to decaffeinate-parser nodes, which also meant that
we had to know up-front when something would be a quasi. Now, we instead find
the unmapped template literal expressions and then map them later. This should
make it easier to handle some remaining cases of empty string interpolations,
and also provide a better path for moving all of the template literal code to
typescript/mappers.
> refactor: change template literal handling to operate on CoffeeScript nodes

- src/parser.js
Everything seems to be working on the decaffeinate test suite and my codebase,
so seems like it's safe to release and try out on all example projects.
I'm still leaving all other code in place for now so that it's easy to switch
back if necessary.
> feat: disable the fallback code by default

- src/mappers/mapBlock.ts
- src/mappers/mapClass.ts
- src/mappers/mapCode.ts
- src/util/ParseContext.ts
- test/examples/class-with-conditional-bound-method/input.coffee
- test/examples/class-with-conditional-bound-method/output.json
- test/examples/class-with-conditional-method/input.coffee
- test/examples/class-with-conditional-method/output.json
- test/examples/class-with-explicit-object-literal/input.coffee
- test/examples/class-with-explicit-object-literal/output.json
- test/examples/class-with-implicit-object-literal-within-function/input.coffee
- test/examples/class-with-implicit-object-literal-within-function/output.json
- test/examples/class-with-outer-assign-blocking-conditional-assign/input.coffee
- test/examples/class-with-outer-assign-blocking-conditional-assign/output.json
Rather than just looking at top-level class statements, we need to traverse all
nested code within classes to distinguish object literals from class proto
assign ops, and we also need to collect all bound methods that we see and the
constructor. Since this happens at different levels of the AST, I needed to make
traversal stateful by adding some state to the context.
> fix: properly traverse nested blocks within class bodies

- src/mappers/mapArr.ts
- src/mappers/mapAssign.ts
- src/mappers/mapBlock.ts
- src/mappers/mapBool.ts
- src/mappers/mapCall.ts
- src/mappers/mapClass.ts
- src/mappers/mapCode.ts
- src/mappers/mapExistence.ts
- src/mappers/mapExpansion.ts
- src/mappers/mapExtends.ts
- src/mappers/mapFor.ts
- src/mappers/mapIf.ts
- src/mappers/mapIn.ts
- src/mappers/mapLiteral.ts
- src/mappers/mapNull.ts
- src/mappers/mapObj.ts
- src/mappers/mapOp.ts
- src/mappers/mapParam.ts
- src/mappers/mapRange.ts
- src/mappers/mapReturn.ts
- src/mappers/mapSplat.ts
- src/mappers/mapSwitch.ts
- src/mappers/mapThrow.ts
- src/mappers/mapTry.ts
- src/mappers/mapUndefined.ts
- src/mappers/mapValue.ts
- src/mappers/mapWhile.ts
- src/nodes.ts
- src/util/getLocation.ts
I want `Node` to be abstract, but `mapBase` was returning an instance of `Node`
as a way to return the location information. Now, we don't view it as a mapper
anymore and just return a custom `NodeLocation` type.
> refactor: change mapBase to getLocation

- src/nodes.ts
- src/util/ParseContext.ts
I think this may have been for compatibility and doesn't seem to be needed
anymore.
> refactor: get rid of RealNode interface

- src/nodes.ts
- test/test.ts
This should make it easier to traverse ASTs when depending only on
decaffeinate-parser.
Also change test traversal to use this new method, so that our tests make sure
every node is covered. (`stripExtraInfo` also had the wrong type before, so this
makes it so the param is actually always `Node`.)
Traverse function and parent pointers coming soon.
> feat: add getChildren and getChildFields methods to Node

- src/nodes.ts
This is needed for some use cases where we want to use the name of the child,
not just the value.
I wanted to use `Array<keyof this>` everywhere, but it turns out that doesn't
work super-well with inheritance, so I can only use it for derived classes and
use `Array<string>` for base classes.
> feat: add a getChildNames method

- .travis.yml
- yarn.lock
We need node 8 for semantic-release to work, and it's a good idea to add it
anyway. Note that this works with travis_after_all since the first build is
always the build leader, but it's possible we can/should get rid of that, but
I'll do the easy thing for now.
Also fix an issue with the lockfile being non-canonical, presumably due to a
greenkeeper issue.
> fix: add node 8 to the travis build

- package.json
- src/mappers/mapAny.ts
- src/mappers/mapModuleDeclaration.ts
- src/nodes.ts
- test/examples/export-assignment/input.coffee
- test/examples/export-assignment/output.json
- test/examples/export-default/input.coffee
- test/examples/export-default/output.json
- test/examples/export-multiple-bindings/input.coffee
- test/examples/export-multiple-bindings/output.json
- test/examples/export-star/input.coffee
- test/examples/export-star/output.json
- test/examples/import-default/input.coffee
- test/examples/import-default/output.json
- test/examples/import-named-with-alias/input.coffee
- test/examples/import-named-with-alias/output.json
- test/examples/import-star/input.coffee
- test/examples/import-star/output.json
- yarn.lock
Progress toward https://github.com/decaffeinate/decaffeinate/issues/427
The AST format is a little simpler than what CoffeeScript uses, partly because
we won't need to transform much, and partly to make the type signatures more
precise.
> feat: add parsing for import and export declarations

- src/mappers/mapBlock.ts
- src/mappers/mapObj.ts
- src/parseCS1AsCS2.ts
- test/examples/function-ending-in-block-comment/output.json
- test/examples/function-followed-by-block-comment/output.json
CS2 doesn't provide as much location information when a comment is at the end of
a function block, but also is less strict about block comment positioning. In
CS1, we need to be careful to end the function in a place that doesn't leave a
stray indented block comment, so we track CS1 comments and remove them in an
intermediate state so that function bounds are more accurate.
> fix: improve CS1 function ranges

- src/mappers/mapAny.ts
- src/mappers/mapSuper.ts
- src/mappers/mapValue.ts
- test/cs2-examples/super-index-access/input.coffee
- test/cs2-examples/super-index-access/output.json
- test/cs2-examples/super-property-access/input.coffee
- test/cs2-examples/super-property-access/output.json
In CS1, super was always a function call, but not it can be a property or index
access, so we need to properly handle that case, which ends up being very
similar to Value handling.
> feat: add parsing for CS2 super nodes

- src/util/expandToIncludeParens.ts
- src/util/fixLocations.ts
- src/util/getLocation.ts
- src/util/locationDataFromSourceRange.ts
- src/util/sourceRangeFromLocationData.ts
- test/examples/parenthesized-break-in-postfix-while/input.coffee
- test/examples/parenthesized-break-in-postfix-while/output.json
This fixes cases like `(break) while true` in CS2, where the new AST was
treating `break` as its own block and there was no source index to use to expand
the whole loop to start at the open-paren. Now, we always expand blocks to
include their surrounding parens, which seems to make sense in general.
> fix: expand block node locations to include surrounding parens

- package.json
- src/mappers/mapBlock.ts
- src/mappers/mapCode.ts
- src/nodes.ts
- test/cs2-examples/await-bound-function/input.coffee
- test/cs2-examples/await-bound-function/output.json
- test/cs2-examples/await-return/output.json
- yarn.lock
The CS AST already marks async functions as such, so we can just use that flag.
> feat: add nodes for async functions

- yarn.lock
Somehow, 655f568 modified yarn.lock to point decaffeinate-coffeescript at decaffeinate-coffeescript2. Maybe this was a yarn bug, since I can't really explain how else it would work and then stop working later with no changes to this file. Whatever the exact cause, this should fix it.
> chore(package): manually fix yarn.lock

- src/mappers/mapModuleDeclaration.ts
- test/__snapshots__/examples.test.ts.snap
- test/examples/export-default-from-source.coffee
See https://github.com/decaffeinate/decaffeinate/issues/1367
> fix: add support for `export { default } from './source'`

- README.md
Using dependabot now since it was acquired by Github.
> doc: remove greenkeeper badge

- package.json
- yarn.lock
CSR beta8 references cscodegen with the unauthenticated `git://` protocol. Github removed support for this in September 2021: https://github.blog/2021-09-01-improving-git-protocol-security-github/. The unpublished CSR beta9 uses the supported `git+https://` protocol, so we now reference that.
> chore: update `coffee-script-redux`

- .circleci/config.yml
The previous build hit the error from this: https://github.com/pnpm/pnpm/issues/3319
> ci(pnpm): install `pnpm` separately from dependencies
